version: "3.9"

services:
  app:
    build: .
    container_name: bank_rest_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bankdb
      - SPRING_DATASOURCE_USERNAME=aslantynyshtyk
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bank_rest_db
    restart: always
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: aslantynyshtyk
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
